# Generated by Django 4.0.4 on 2022-05-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vopros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quetion',
            options={'ordering': ['time_create', 'tittle'], 'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество статей'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, verbose_name='Категория'),
        ),
    ]
