# Generated by Django 4.0.4 on 2022-05-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vopros', '0002_alter_quetion_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(blank=True, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='quetionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vopros.quetion', verbose_name='id вопроса'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='tume_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
    ]
