# Generated by Django 4.0.4 on 2022-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vopros', '0003_alter_answer_content_alter_answer_quetionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quetion',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='quetion',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/&d', verbose_name='Фото'),
        ),
    ]
