# Generated by Django 4.0.4 on 2022-05-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vopros', '0004_alter_quetion_content_alter_quetion_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quetion',
            options={'ordering': ['-time_create', 'tittle'], 'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='quetion',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
