# Generated by Django 4.0.4 on 2022-05-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vopros', '0005_alter_quetion_options_alter_quetion_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quetion',
            name='isPublished',
        ),
        migrations.AlterField(
            model_name='quetion',
            name='isSolved',
            field=models.BooleanField(default=False, verbose_name='Решено'),
        ),
    ]
