# Generated by Django 4.0.4 on 2022-05-21 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, verbose_name='Категория')),
                ('count', models.IntegerField(default=0, verbose_name='Количество статей')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='Quetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/&d', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('isSolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tag_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vopros.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-time_create', 'tittle'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='ответ')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('tume_update', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('quetionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vopros.quetion', verbose_name='id вопроса')),
            ],
        ),
    ]
